# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  - master
  - releases/*

variables:
  project: 'TeximpNet'
  testProject: 'TeximpNet.Test'

jobs:
- job: Linux_x64
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: CmdLine@2
    inputs:
      script: |
        dotnet build $(project) -f netstandard1.3 -c Release    
        dotnet build $(testProject) -c Release   
        dotnet test $(testProject) -c Release
- job: MacOS_x64
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: CmdLine@2
    inputs:
      script: |
        dotnet build $(project) -f netstandard1.3 -c Release   
        dotnet build $(testProject) -c Release  
        dotnet test $(testProject) -c Release
- job: Windows_x64
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: CmdLine@2
    inputs:
      script: |
        dotnet build $(project)    
        dotnet build $(testProject)   
        dotnet test $(testProject) -c Release -f netcoreapp3.1 -- RunConfiguration.TargetPlatform=x64
        dotnet test $(testProject) -c Debug -f net48 -- RunConfiguration.TargetPlatform=x86
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(project)/bin/Release'
      Contents: |
        *.nupkg
        *.snupkg
        UnityPlugin
      TargetFolder: 'artifacts'
      CleanTargetFolder: true
      OverWrite: true
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'artifacts'
      ArtifactName: '$(project)'
      publishLocation: 'Container'